#!/bin/bash
# OCI Setup Helper for RHCSA Practice Labs
# This script helps configure OCI credentials

set -e

OCI_DIR="$HOME/.oci"
KEY_FILE="$OCI_DIR/oci_api_key.pem"
CONFIG_FILE="$OCI_DIR/config"

echo "=== RHCSA Practice Labs - OCI Setup ==="
echo ""

# Create OCI directory
if [ ! -d "$OCI_DIR" ]; then
    echo "Creating $OCI_DIR directory..."
    mkdir -p "$OCI_DIR"
    chmod 700 "$OCI_DIR"
fi

# Check for existing config
if [ -f "$CONFIG_FILE" ]; then
    echo "Found existing OCI config at $CONFIG_FILE"
    echo "Contents:"
    echo "---"
    grep -v "key_file\|pass_phrase" "$CONFIG_FILE" || true
    echo "---"
    echo ""
    read -p "Overwrite existing config? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing config."
        exit 0
    fi
fi

echo ""
echo "You'll need the following from Oracle Cloud Console:"
echo "  1. Tenancy OCID (Profile > Tenancy > OCID)"
echo "  2. User OCID (Profile > User Settings > OCID)"
echo "  3. Region (e.g., us-ashburn-1)"
echo "  4. Compartment OCID (or use tenancy OCID for root)"
echo ""
echo "If you haven't created an API key yet:"
echo "  1. Go to Profile > User Settings > API Keys"
echo "  2. Click 'Add API Key' > 'Generate API Key Pair'"
echo "  3. Download the private key"
echo "  4. Note the fingerprint shown"
echo ""

read -p "Enter Tenancy OCID: " TENANCY_OCID
read -p "Enter User OCID: " USER_OCID
read -p "Enter Region (e.g., us-ashburn-1): " REGION
read -p "Enter API Key Fingerprint: " FINGERPRINT
read -p "Enter Compartment OCID (or press Enter for tenancy): " COMPARTMENT_OCID

COMPARTMENT_OCID=${COMPARTMENT_OCID:-$TENANCY_OCID}

# Check for private key
if [ ! -f "$KEY_FILE" ]; then
    echo ""
    echo "Private key not found at $KEY_FILE"
    read -p "Enter path to your OCI private key: " KEY_PATH
    if [ -f "$KEY_PATH" ]; then
        cp "$KEY_PATH" "$KEY_FILE"
        chmod 600 "$KEY_FILE"
        echo "Copied key to $KEY_FILE"
    else
        echo "ERROR: Key file not found at $KEY_PATH"
        exit 1
    fi
fi

# Create OCI CLI config
cat > "$CONFIG_FILE" << EOF
[DEFAULT]
user=$USER_OCID
fingerprint=$FINGERPRINT
tenancy=$TENANCY_OCID
region=$REGION
key_file=$KEY_FILE
EOF

chmod 600 "$CONFIG_FILE"

echo ""
echo "Created $CONFIG_FILE"

# Create Terraform tfvars
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(dirname "$SCRIPT_DIR")/infra"
TFVARS_FILE="$INFRA_DIR/terraform.tfvars"

cat > "$TFVARS_FILE" << EOF
# OCI Credentials (generated by oci-setup.sh)
tenancy_ocid     = "$TENANCY_OCID"
user_ocid        = "$USER_OCID"
fingerprint      = "$FINGERPRINT"
private_key_path = "$KEY_FILE"
region           = "$REGION"
compartment_ocid = "$COMPARTMENT_OCID"

# Compute Configuration - Free Tier
instance_shape = "VM.Standard.E2.1.Micro"

# Session defaults
session_id              = "test"
session_timeout_minutes = 30
EOF

echo "Created $TFVARS_FILE"

# Validate
echo ""
echo "Validating Terraform configuration..."
cd "$INFRA_DIR"
terraform init -upgrade > /dev/null 2>&1
if terraform validate > /dev/null 2>&1; then
    echo "✓ Terraform configuration is valid"
else
    echo "✗ Terraform validation failed - check credentials"
    terraform validate
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "To test your setup:"
echo "  cd infra"
echo "  terraform plan -var='session_id=test'"
echo ""
echo "To create a practice session:"
echo "  terraform apply -var='session_id=test'"
echo ""
echo "To destroy resources:"
echo "  terraform destroy -var='session_id=test'"
