#!/bin/bash
# RHCSA Practice Labs - OCI Setup Script
# This script helps configure Oracle Cloud Infrastructure for the practice labs.

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}RHCSA Practice Labs - OCI Setup${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check prerequisites
echo -e "${YELLOW}Checking prerequisites...${NC}"

check_command() {
    if command -v "$1" &>/dev/null; then
        echo -e "  ${GREEN}✓${NC} $1 found"
        return 0
    else
        echo -e "  ${RED}✗${NC} $1 not found"
        return 1
    fi
}

PREREQS_OK=true
check_command terraform || PREREQS_OK=false
check_command oci || PREREQS_OK=false
check_command python3 || PREREQS_OK=false
check_command ssh || PREREQS_OK=false

if [ "$PREREQS_OK" = false ]; then
    echo ""
    echo -e "${RED}Missing prerequisites. Please install:${NC}"
    echo "  - terraform: https://www.terraform.io/downloads"
    echo "  - oci-cli: pip install oci-cli"
    echo "  - python3: apt install python3 / brew install python3"
    exit 1
fi

echo ""

# Check OCI CLI configuration
echo -e "${YELLOW}Checking OCI CLI configuration...${NC}"

if [ -f ~/.oci/config ]; then
    echo -e "  ${GREEN}✓${NC} ~/.oci/config found"
    
    # Try to get tenancy info
    if oci iam tenancy get --query 'data.name' --raw-output 2>/dev/null; then
        echo -e "  ${GREEN}✓${NC} OCI CLI authentication working"
    else
        echo -e "  ${RED}✗${NC} OCI CLI authentication failed"
        echo "    Run: oci setup config"
        exit 1
    fi
else
    echo -e "  ${RED}✗${NC} ~/.oci/config not found"
    echo ""
    echo "Please set up OCI CLI first:"
    echo "  1. Create OCI account: https://www.oracle.com/cloud/free/"
    echo "  2. Generate API key in OCI Console → Identity → Users → API Keys"
    echo "  3. Run: oci setup config"
    exit 1
fi

echo ""

# Check/create terraform.tfvars
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="${SCRIPT_DIR}/../infra"
TFVARS_FILE="${INFRA_DIR}/terraform.tfvars"

echo -e "${YELLOW}Checking Terraform configuration...${NC}"

if [ -f "$TFVARS_FILE" ]; then
    echo -e "  ${GREEN}✓${NC} terraform.tfvars exists"
else
    echo -e "  ${YELLOW}!${NC} terraform.tfvars not found, creating..."
    
    # Extract values from OCI config
    OCI_CONFIG=~/.oci/config
    TENANCY_OCID=$(grep -E '^tenancy' "$OCI_CONFIG" | head -1 | cut -d= -f2 | tr -d ' ')
    USER_OCID=$(grep -E '^user' "$OCI_CONFIG" | head -1 | cut -d= -f2 | tr -d ' ')
    FINGERPRINT=$(grep -E '^fingerprint' "$OCI_CONFIG" | head -1 | cut -d= -f2 | tr -d ' ')
    KEY_FILE=$(grep -E '^key_file' "$OCI_CONFIG" | head -1 | cut -d= -f2 | tr -d ' ')
    REGION=$(grep -E '^region' "$OCI_CONFIG" | head -1 | cut -d= -f2 | tr -d ' ')
    
    # Get compartment (use tenancy root if not specified)
    COMPARTMENT_OCID="$TENANCY_OCID"
    
    echo "  Extracted from ~/.oci/config:"
    echo "    Tenancy: ${TENANCY_OCID:0:20}..."
    echo "    User: ${USER_OCID:0:20}..."
    echo "    Region: $REGION"
    
    cat > "$TFVARS_FILE" << EOF
# OCI Configuration for RHCSA Practice Labs
# Auto-generated by setup-oci.sh

tenancy_ocid     = "$TENANCY_OCID"
user_ocid        = "$USER_OCID"
fingerprint      = "$FINGERPRINT"
private_key_path = "$KEY_FILE"
region           = "$REGION"
compartment_ocid = "$COMPARTMENT_OCID"
EOF
    
    echo -e "  ${GREEN}✓${NC} Created terraform.tfvars"
fi

echo ""

# Initialize Terraform
echo -e "${YELLOW}Initializing Terraform...${NC}"
cd "$INFRA_DIR"

if [ -d .terraform ]; then
    echo -e "  ${GREEN}✓${NC} Terraform already initialized"
else
    terraform init
    echo -e "  ${GREEN}✓${NC} Terraform initialized"
fi

echo ""

# Validate configuration
echo -e "${YELLOW}Validating Terraform configuration...${NC}"
if terraform validate; then
    echo -e "  ${GREEN}✓${NC} Configuration valid"
else
    echo -e "  ${RED}✗${NC} Configuration invalid"
    exit 1
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Setup complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Next steps:"
echo "  1. Start the application: python api/app_socketio.py"
echo "  2. Open http://localhost:8080 in your browser"
echo "  3. Go to Settings and click 'Create Cloud Session'"
echo "  4. Wait ~2 minutes for VMs to provision"
echo "  5. Practice RHCSA tasks with real cloud VMs!"
echo ""
echo "Note: OCI Free Tier includes 2 always-free VMs."
echo "Sessions auto-terminate after 30 minutes of inactivity."
